language: csharp
# Mono is used to build .NET on Linux--we don't need it with Core.
mono: none
# Needed to run commands in the Xenial CLI
sudo: required
# The version of Ubuntu to run the Travis virtual machine -- needed for .NET Core
dist: xenial
# Your SDK version, not your run-time version
dotnet: 2.2 
git:
  depth: false
script: 
  - cd /home/travis/build/HilarySAccenture/IconPractice/Scripts/
  - ./StartDockerIcon
  - ./RunIntegrationTests
  

